repos:
  - repo: https://github.com/ambv/black
    rev: stable
    hooks:
      - id: black
        language_version: python3.7

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: flake8
  - repo: local
    hooks:
    - id: tests
      name: run tests
      entry: pytest --cov
      language: system
      types: [python]
      stages: [push]
